# Generated by Django 4.2.11 on 2024-04-22 05:52

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_post_content_alter_reply_post_onetimecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimecode',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 5, 53, 27, 11128, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
